### ISSUE TITLE
Secrets read function

### ISSUE THREAD

**Issue by ewilde** [openfaas-incubator/go-function-sdk#4]
# Summary

Add support for reading functions to this SDK

Or 

Is it better to use the SDK package from [openfaas-cloud](https://github.com/openfaas/openfaas-cloud/blob/master/sdk/secrets.go) and update the README.md here to sign post?

**Comment by alexellis** [comment]
That's a great question.

Is option 2 easier for the time-being? Very easy to merge that and add value.
